USE platziblog;

CREATE TABLE posts_labels(
id_postsLabels INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
idPosts INT NOT NULL,
idLabels INT NOT NULL,
FOREIGN KEY (idPosts) REFERENCES posts(id_posts) ON UPDATE CASCADE ON DELETE NO ACTION,
FOREIGN KEY (idLabels) REFERENCES labels(id_labels) ON UPDATE CASCADE ON DELETE NO ACTION
);
