CREATE SCHEMA platziblog DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

USE platziblog;

CREATE TABLE users(
id_users INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
login VARCHAR(30) NOT NULL,
password VARCHAR(32) NOT NULL,
nickname  VARCHAR(40) NOT NULL UNIQUE,
email VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE categories(
id_categories INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name_category VARCHAR(30) NOT NULL
);

CREATE TABLE labels(
id_labels INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name_label VARCHAR(30) NOT NULL
);
